const sampleUsers = [
  {
    username: "ahmed_hassan",
    hoursWorked: 100,
    email: "ahmed.hassan@example.com",
    password: "hashed_password_1",
    role: "admin",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 1000,
    timeRecords: []
  },
  {
    username: "sara_khan",
    hoursWorked: 10,
    email: "sara.khan@example.com",
    password: "hashed_password_2",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 50,
    timeRecords: []
  },
  {
    username: "mohamed_ali",
    hoursWorked: 20,
    email: "mohamed.ali@example.com",
    password: "hashed_password_3",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 100,
    timeRecords: []
  },
  {
    username: "ayesha_rahman",
    hoursWorked: 15,
    email: "ayesha.rahman@example.com",
    password: "hashed_password_4",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 80,
    timeRecords: []
  },
  {
    username: "zain_malik",
    hoursWorked: 150,
    email: "zain.malik@example.com",
    password: "hashed_password_5",
    role: "admin",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 1500,
    timeRecords: []
  },
  {
    username: "fatima_abdul",
    hoursWorked: 25,
    email: "fatima.abdul@example.com",
    password: "hashed_password_6",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 120,
    timeRecords: []
  },
  {
    username: "omar_kareem",
    hoursWorked: 30,
    email: "omar.kareem@example.com",
    password: "hashed_password_7",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 150,
    timeRecords: []
  },
  {
    username: "amna_tariq",
    hoursWorked: 5,
    email: "amna.tariq@example.com",
    password: "hashed_password_8",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 25,
    timeRecords: []
  },
  {
    username: "faraz_ahmed",
    hoursWorked: 200,
    email: "faraz.ahmed@example.com",
    password: "hashed_password_9",
    role: "admin",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 2000,
    timeRecords: []
  },
  {
    username: "lubna_shahid",
    hoursWorked: 12,
    email: "lubna.shahid@example.com",
    password: "hashed_password_10",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 60,
    timeRecords: []
  },
  {
    username: "khalid_siddiq",
    hoursWorked: 18,
    email: "khalid.siddiq@example.com",
    password: "hashed_password_11",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 90,
    timeRecords: []
  },
  {
    username: "noor_fatima",
    hoursWorked: 40,
    email: "noor.fatima@example.com",
    password: "hashed_password_12",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 200,
    timeRecords: []
  },
  {
    username: "saad_ahmed",
    hoursWorked: 7,
    email: "saad.ahmed@example.com",
    password: "hashed_password_13",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 35,
    timeRecords: []
  },
  {
    username: "mariam_rashid",
    hoursWorked: 180,
    email: "mariam.rashid@example.com",
    password: "hashed_password_14",
    role: "admin",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 1800,
    timeRecords: []
  },
  {
    username: "danish_hasan",
    hoursWorked: 22,
    email: "danish.hasan@example.com",
    password: "hashed_password_15",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 110,
    timeRecords: []
  }
];


module.exports = sampleUsers;
