const sampleUsers = [
  {
    username: "john_doe",
    hoursWorked: 15,
    points: 150,
    email: "john.doe@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 150,
    timeRecords: []
  },
  {
    username: "jane_smith",
    hoursWorked: 20,
    points: 200,
    email: "jane.smith@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 200,
    timeRecords: []
  },
  {
    username: "admin_user",
    hoursWorked: 0,
    points: 0,
    email: "admin@example.com",
    password: "admin123",
    role: "admin",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 0,
    timeRecords: []
  },
  {
    username: "emma_watson",
    hoursWorked: 10,
    points: 100,
    email: "emma.watson@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 100,
    timeRecords: []
  },
  {
    username: "charlie_brown",
    hoursWorked: 12,
    points: 120,
    email: "charlie.brown@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 120,
    timeRecords: []
  },
  {
    username: "lucy_gray",
    hoursWorked: 18,
    points: 180,
    email: "lucy.gray@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 180,
    timeRecords: []
  },
  {
    username: "michael_scott",
    hoursWorked: 25,
    points: 250,
    email: "michael.scott@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 250,
    timeRecords: []
  },
  {
    username: "pam_beesly",
    hoursWorked: 22,
    points: 220,
    email: "pam.beesly@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 220,
    timeRecords: []
  },
  {
    username: "jim_halpert",
    hoursWorked: 30,
    points: 300,
    email: "jim.halpert@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 300,
    timeRecords: []
  },
  {
    username: "dwight_schrute",
    hoursWorked: 40,
    points: 400,
    email: "dwight.schrute@example.com",
    password: "password123",
    role: "volunteer",
    tasks: [],
    events: [],
    profileImage: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    totalPoints: 400,
    timeRecords: []
  }
];

module.exports = sampleUsers;
