const sampleEvents = [
  {
    name: "Friday Jummah Prayer",
    date: "2023-12-15T12:30:00Z",
    type: "Religious",
    time: "12:30 PM",
    location: "Main Prayer Hall",
    description: "Join the weekly Jummah prayer and sermon.",
    points: 10,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 5,
    volunteersAssigned: []
  },
  {
    name: "Youth Quran Recitation",
    date: "2023-12-16T17:00:00Z",
    type: "Educational",
    time: "05:00 PM",
    location: "Community Room",
    description: "A Quran recitation session for youth.",
    points: 8,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 3,
    volunteersAssigned: []
  },
  {
    name: "Islamic Lecture Series",
    date: "2023-12-17T18:30:00Z",
    type: "Educational",
    time: "06:30 PM",
    location: "Main Hall",
    description: "A lecture series on Islamic history and values.",
    points: 12,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 4,
    volunteersAssigned: []
  },
  {
    name: "Monthly Community Dinner",
    date: "2023-12-18T19:00:00Z",
    type: "Social",
    time: "07:00 PM",
    location: "Dining Hall",
    description: "A dinner gathering to connect with the community.",
    points: 7,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 6,
    volunteersAssigned: []
  },
  {
    name: "Charity Drive for Winter Clothing",
    date: "2023-12-19T10:00:00Z",
    type: "Charity",
    time: "10:00 AM",
    location: "Community Center",
    description: "Help distribute winter clothing to those in need.",
    points: 15,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 10,
    volunteersAssigned: []
  },
  {
    name: "Eid Prayer",
    date: "2023-12-20T07:00:00Z",
    type: "Religious",
    time: "07:00 AM",
    location: "Open Ground",
    description: "Celebrate Eid with a congregation prayer.",
    points: 20,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 15,
    volunteersAssigned: []
  },
  {
    name: "Taraweeh Prayer",
    date: "2023-12-21T20:00:00Z",
    type: "Religious",
    time: "08:00 PM",
    location: "Main Prayer Hall",
    description: "Special nightly prayers during Ramadan.",
    points: 10,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 4,
    volunteersAssigned: []
  },
  {
    name: "Kids Islamic Workshop",
    date: "2023-12-22T15:00:00Z",
    type: "Educational",
    time: "03:00 PM",
    location: "Community Room",
    description: "An engaging workshop for kids on Islamic teachings.",
    points: 6,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 5,
    volunteersAssigned: []
  },
  {
    name: "Quran Memorization Contest",
    date: "2023-12-23T11:00:00Z",
    type: "Competition",
    time: "11:00 AM",
    location: "Main Hall",
    description: "A contest to encourage Quran memorization among youth.",
    points: 15,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 6,
    volunteersAssigned: []
  },
  {
    name: "Zakat Collection and Distribution",
    date: "2023-12-24T10:00:00Z",
    type: "Charity",
    time: "10:00 AM",
    location: "Mosque Office",
    description: "Assist in collecting and distributing Zakat.",
    points: 12,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 8,
    volunteersAssigned: []
  },
  {
    name: "Community Cleanup",
    date: "2023-12-25T09:00:00Z",
    type: "Social",
    time: "09:00 AM",
    location: "Mosque Grounds",
    description: "Help clean up the mosque grounds and surroundings.",
    points: 10,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 8,
    volunteersAssigned: []
  },
  {
    name: "Volunteer Appreciation Night",
    date: "2023-12-26T19:00:00Z",
    type: "Social",
    time: "07:00 PM",
    location: "Community Hall",
    description: "An event to recognize and appreciate volunteers.",
    points: 5,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 3,
    volunteersAssigned: []
  },
  {
    name: "Ramadan Preparation Meeting",
    date: "2023-12-27T14:00:00Z",
    type: "Planning",
    time: "02:00 PM",
    location: "Mosque Office",
    description: "Plan activities and logistics for Ramadan.",
    points: 8,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 5,
    volunteersAssigned: []
  },
  {
    name: "Food Drive",
    date: "2023-12-28T13:00:00Z",
    type: "Charity",
    time: "01:00 PM",
    location: "Mosque Parking Lot",
    description: "Distribute food packs to families in need.",
    points: 12,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 10,
    volunteersAssigned: []
  },
  {
    name: "Volunteer Training Session",
    date: "2023-12-29T10:00:00Z",
    type: "Educational",
    time: "10:00 AM",
    location: "Community Room",
    description: "Train volunteers on event management and safety.",
    points: 8,
    totalAttended: 0,
    totalSignUp: 0,
    volunteersNeeded: 5,
    volunteersAssigned: []
  }
];



module.exports = sampleEvents;
